# Generated by Django 6.0.3 on 2026-05-17 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('raw_vt_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('abuse_score', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('ports_count', models.IntegerField(default=0)),
                ('raw_abuse_data', models.JSONField(blank=True, null=True)),
                ('raw_shodan_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('IP', 'IP'), ('URL', 'URL'), ('FILE', 'FILE')], max_length=10)),
                ('target', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('malicious_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('raw_vt_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScanHistory',
        ),
    ]
