# Generated by Django 6.0.3 on 2026-05-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_filescan_ipscan_profile_scanlog_urlscan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileScan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScanLog',
        ),
        migrations.DeleteModel(
            name='URLScan',
        ),
        migrations.RenameField(
            model_name='ipscan',
            old_name='raw_abuse_data',
            new_name='raw_abuse',
        ),
        migrations.RenameField(
            model_name='ipscan',
            old_name='raw_shodan_data',
            new_name='raw_shodan',
        ),
        migrations.RemoveField(
            model_name='ipscan',
            name='isp',
        ),
        migrations.RemoveField(
            model_name='ipscan',
            name='ports_count',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
