# Generated by Django 6.0.3 on 2026-05-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_delete_filescan_remove_profile_user_delete_scanlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('malicious_count', models.IntegerField(default=0)),
                ('harmless_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('raw_virustotal', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
