# Generated by Django 6.0.3 on 2026-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_urlscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(default='Suspicious Activity // Tactical Intel Block', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=50)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('verdict', models.CharField(default='clean', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('malicious_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('clean_count', models.IntegerField(default=0)),
                ('total_engines', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='Generic Binary', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
