# Generated by Django 6.0.3 on 2026-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_company_userprofile_first_name_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='establishment_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('sme', 'SME'), ('corporation', 'Corporation'), ('government', 'Government'), ('education', 'Education'), ('nonprofit', 'Non-Profit')], default='startup', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment',
            field=models.CharField(blank=True, help_text='School/University/Company Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('researcher', 'Researcher'), ('professional', 'Security Professional'), ('pentester', 'Penetration Tester'), ('soc_analyst', 'SOC Analyst'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistedip',
            name='reason',
            field=models.CharField(default='Suspicious Activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan - 100 scans/month'), ('basic', 'Basic Plan - 500 scans/month'), ('professional', 'Professional Plan - 5000 scans/month'), ('enterprise', 'Enterprise Plan - Unlimited scans')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
