# Generated by Django 6.0.5 on 2026-05-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_honeypotlog_honeypotport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
